import { IProject } from "@/types/project.types";

export const demoProjectResponse: IProject[] = [
  {
    id: "1",
    createdBy: "user1",
    name: "E-commerce Website",
    description: "A full-stack e-commerce web application.",
    members: ["user2", "user3"],
    teamId: "team1",
    deadline: ["2024-07-15"],
    status: "completed",
    createdAt: "2024-06-01",
    updatedAt: "2024-06-10",
  },
  {
    id: "2",
    createdBy: "user4",
    name: "CRM Dashboard",
    description: "A customer relationship management system.",
    members: ["user5", "user6"],
    teamId: "team2",
    deadline: ["2024-08-01"],
    status: "pastDue",
    createdAt: "2024-06-05",
    updatedAt: "2024-06-12",
  },
  {
    id: "3",
    createdBy: "user7",
    name: "Social Media App",
    description: "A mobile app for social networking.",
    members: ["user8", "user9"],
    teamId: "team3",
    deadline: ["2024-09-10"],
    status: "pending",
    createdAt: "2024-06-08",
    updatedAt: "2024-06-15",
  },
  {
    id: "4",
    createdBy: "user10",
    name: "Inventory Management System",
    description: "A system for tracking inventory.",
    members: ["user11", "user12"],
    teamId: "team4",
    deadline: ["2024-07-20"],
    status: "completed",
    createdAt: "2024-06-10",
    updatedAt: "2024-06-18",
  },
  {
    id: "5",
    createdBy: "user13",
    name: "Online Learning Platform",
    description: "A platform for online courses.",
    members: ["user14", "user15"],
    teamId: "team5",
    deadline: ["2024-08-15"],
    status: "completed",
    createdAt: "2024-06-12",
    updatedAt: "2024-06-20",
  },
  {
    id: "6",
    createdBy: "user16",
    name: "Event Management App",
    description: "A tool to organize events efficiently.",
    members: ["user17", "user18"],
    teamId: "team6",
    deadline: ["2024-07-30"],
    status: "completed",
    createdAt: "2024-06-14",
    updatedAt: "2024-06-22",
  },
  {
    id: "7",
    createdBy: "user19",
    name: "AI Chatbot",
    description: "A chatbot for automated customer support.",
    members: ["user20", "user21"],
    teamId: "team7",
    deadline: ["2024-09-01"],
    status: "completed",
    createdAt: "2024-06-16",
    updatedAt: "2024-06-25",
  },
  {
    id: "8",
    createdBy: "user22",
    name: "Health Tracking App",
    description: "A mobile app for tracking health metrics.",
    members: ["user23", "user24"],
    teamId: "team8",
    deadline: ["2024-10-10"],
    status: "pastDue",
    createdAt: "2024-06-18",
    updatedAt: "2024-06-26",
  },
  {
    id: "9",
    createdBy: "user25",
    name: "Blockchain Payment System",
    description: "A decentralized payment gateway.",
    members: ["user26", "user27"],
    teamId: "team9",
    deadline: ["2024-09-20"],
    status: "completed",
    createdAt: "2024-06-20",
    updatedAt: "2024-06-28",
  },
  {
    id: "10",
    createdBy: "user28",
    name: "Fitness Tracker",
    description: "An app to track daily fitness activities.",
    members: ["user29", "user30"],
    teamId: "team10",
    deadline: ["2024-08-25"],
    status: "completed",
    createdAt: "2024-06-22",
    updatedAt: "2024-06-30",
  },
];
