export const ENV = {
  APP_PORT: process.env.APP_PORT,
  APP_COOKIE_SECRET: process.env.COOKIE_SECRET,
  APP_SOCKET_PATH: process.env.APP_SOCKET_PATH,
  APP_COOKIE_DOMAIN:
    process.env.NODE_ENV === "pro"
      ? process.env.PRO_COOKIE_DOMAIN
      : process.env.DEV_COOKIE_DOMAIN,
  APP_EMAIL: process.env.EMAIL,
  APP_PASSWORD: process.env.APP_PASSWORD,

  // Frontend
  CLIENT_URL: process.env.CLIENT_URL?.split(",") || [],

  // Firebase
  FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
  FIREBASE_STRORAGE_BUCKET: process.env.FIREBASE_STRORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID: process.env.FIREBASE_MEASUREMENT_ID,
  FIREBASE_DATABASE_URL: process.env.FIREBASE_DATABASE_URL,
};
