name: Deploy All

on:
  pull_request:
    paths:
      - "frontend/**"
      - "backend/**"
      - "landing-page/**"
    branches:
      - master
    types:
      - closed
  push:
    paths:
      - "frontend/**"
      - "backend/**"
      - "landing-page/**"
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install Dependencies
        run: |
          cd frontend/
          echo "Installing Client Side Dependencies"
          pnpm install --frozen-lockfile

          cd ../backend/
          echo "Installing Backend Dependencies"
          pnpm install --frozen-lockfile

          cd ../landing-page/
          echo "Installing Landing Page Dependencies"
          pnpm install --frozen-lockfile
          cd ../

      - name: Build Client Dashboard
        env:
          DOTENV_KEY: ${{ secrets.FRONTEND_DOTENV_KEY }}
        run: |
          cd frontend/
          pnpm run build || exit 1
          pwd 
          ls -la frontend/

      - name: Build Backend
        env:
          DOTENV_KEY: ${{ secrets.BACKEND_DOTENV_KEY }}
        run: |
          cd backend 
          pwd
          ls -al backend
          echo "${{ secrets.ADMIN_SDK }}" | base64 --decode > admin-sdk.json
          pnpm run build || exit 1

      - name: Add SSH key on Runner
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add VPS Host key to known Hosts
        run: ssh-keyscan -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Create Client Side Deployment Directory on VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo mkdir -p /var/www/youlead/frontend
            sudo chown /var/www/youlead/frontend ${{ secrets.VPS_USER }}
            sudo chmod 755 /var/www/youlead/frontend

      - name: Send Frontend Build Files to VPS
        run: rsync -avz -e "ssh -i ~/.ssh/id_rsa -p ${{ secrets.VPS_PORT }}" frontend/dist/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/youlead/frontend

      - name: Create Server Side Deployment Directory on VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo mkdir -p /var/www/youlead/backend
            sudo chown /var/www/youlead/backend ${{ secrets.VPS_USER }}
            sudo chmod 755 /var/www/youlead/backend

      - name: Send Backend Build Files to VPS
        run: rsync -avz -e "ssh -i ~/.ssh/id_rsa -p ${{ secrets.VPS_PORT }}" backend/dist ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/youlead/backend

      - name: Start Backend
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/youlead/backend
            pnpm install --prod
            pm2 start app.js --name YouLead-Backend
            pm2 save 
            pm2 status

      - name: Create Landing Page Directory on VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo mkdir -p /var/www/youlead/landing-page
            sudo chown ${{ secrets.VPS_USER }}: /var/www/youlead/landing-page 
            sudo chmod 755 /var/www/youlead/landing-page

      - name: Send Landing Page Build Files to VPS
        run: rsync -avz -e "ssh -i ~/.ssh/id_rsa -p ${{ secrets.VPS_PORT }}" landing-page/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/youlead/landing-page

      - name: Start Landing Page
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          scripts: |
            cd /var/www/youlead/landing-page
            pm2 start --name YouLead_NextJS
            pm2 save
            pm2 status

      - name: Restart Nginx
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo service nginx restart
